baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "FabCFO"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["https://cfoclub.co.za/wp-content/uploads/2023/11/cropped-CFO-CLUB-CIBA-logo-raw-2.webp"]